### ISSUE TITLE
Discard current tab doesn't work if previous tab was closed

### ISSUE THREAD

**Issue by arturkohut** [deanoemcke/thegreatdiscarder#1]
Hi.

I have tabs: A, B, C.
Currently, I am on tab A.
Then, I decided to switch to tab B.
Close previous active tab A and press discard current tab (on tab B).
And nothing happened.

**Comment by mohanraj-r** [comment]
I can confirm this behavior. 

My guess - this could be because the extension tries to jump to the last active tab once the current tab is discarded. And when the last active tab is not present anymore, guess the extension fails switching to it instead of going further in the tab stack.

**Comment by mohanraj-r** [comment]
I peeked at the code and looks like a condition needs to be added to https://github.com/deanoemcke/thegreatdiscarder/blob/master/src/js/eventPage.js#L365 to make sure `previousTabId` is still around (Tab status `active`?). 

Also wondering since we have access to the entire list of `tabs` in `discardHighlightedTab()` if we can walk down the list instead of creating a new tab in the else condition?
